//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Behk4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Единица.
    /// </summary>
    // *** Start programmer edit section *** (Единица CustomAttributes)

    // *** End programmer edit section *** (Единица CustomAttributes)
    public enum Единица
    {
        
        // *** Start programmer edit section *** (Единица.Шт CustomAttributes)

        // *** End programmer edit section *** (Единица.Шт CustomAttributes)
        [Caption("Шт")]
        Шт,
        
        // *** Start programmer edit section *** (Единица.Мл CustomAttributes)

        // *** End programmer edit section *** (Единица.Мл CustomAttributes)
        [Caption("Мл")]
        Мл,
        
        // *** Start programmer edit section *** (Единица.Грамм CustomAttributes)

        // *** End programmer edit section *** (Единица.Грамм CustomAttributes)
        [Caption("Грамм")]
        Грамм,
        
        // *** Start programmer edit section *** (Единица.Килограмм CustomAttributes)

        // *** End programmer edit section *** (Единица.Килограмм CustomAttributes)
        [Caption("Килограмм")]
        Килограмм,
        
        // *** Start programmer edit section *** (Единица.Литр CustomAttributes)

        // *** End programmer edit section *** (Единица.Литр CustomAttributes)
        [Caption("Литр")]
        Литр,
    }
}
