//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.DestkijjSad
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ингредиенты.
    /// </summary>
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИнгредиентыE", new string[] {
            "Наименование as \'Наименование\'",
            "Код as \'Код\'"})]
    [View("ИнгредиентыL", new string[] {
            "Наименование as \'Наименование\'",
            "Код as \'Код\'"})]
    public class Ингредиенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fКод;
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Ингредиенты.Код CustomAttributes)

        // *** End programmer edit section *** (Ингредиенты.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Ингредиенты.Код Get start)

                // *** End programmer edit section *** (Ингредиенты.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Ингредиенты.Код Get end)

                // *** End programmer edit section *** (Ингредиенты.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ингредиенты.Код Set start)

                // *** End programmer edit section *** (Ингредиенты.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Ингредиенты.Код Set end)

                // *** End programmer edit section *** (Ингредиенты.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Ингредиенты.Наименование CustomAttributes)

        // *** End programmer edit section *** (Ингредиенты.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Ингредиенты.Наименование Get start)

                // *** End programmer edit section *** (Ингредиенты.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Ингредиенты.Наименование Get end)

                // *** End programmer edit section *** (Ингредиенты.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ингредиенты.Наименование Set start)

                // *** End programmer edit section *** (Ингредиенты.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Ингредиенты.Наименование Set end)

                // *** End programmer edit section *** (Ингредиенты.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИнгредиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнгредиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнгредиентыE", typeof(IIS.DestkijjSad.Ингредиенты));
                }
            }
            
            /// <summary>
            /// "ИнгредиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнгредиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнгредиентыL", typeof(IIS.DestkijjSad.Ингредиенты));
                }
            }
        }
    }
}
